criterion:
  name: ce

# optimizer:
#   name: prodigy
#   lr: 1
#   weight_decay: 0.01

optimizer:
  name: adam
  lr: 0.002
  weight_decay: 0.0001
  grad_clip_value: 1

scheduler:
  name: cosine
  lr_gamma: 0.99
  lr_min: 0.00002

run:
  experiment: "fmnist_cnn_train"
  n_epochs: 50
  batch_size: 32
  use_cuda: 1
  gpu_id: 0
  deterministic: 1
  log_interval: 200
  train_noise: 0
  grad_clip: False
  max_grad_value: 1
  do_distill: False

quantize:
  weight_bit: 8
  input_bit: 8

loginfo: "logs.csv"

noise:
  phase_bias: 0
  phase_noise_std: 0
  gamma_noise_std: 0
  crosstalk_factor: 0.05
  output_noise_std: 0
  random_state: 42
  weight_noise_std: 0.0
  crosstalk_flag: 0
  noise_flag: 0
  crosstalk_scheduler:
    interv_h: 20
    interv_v: 120
    interv_s: 9
    ps_width: 6

checkpoint:
  save_best_model_k: 3
  checkpoint_dir: "fmnist/cnn/train"
  model_comment: ""
  resume: 0
  restore_checkpoint : ""

model:
  name: "TeMPO_CNN"
  conv_cfg:
    type: TeMPOBlockConv2d
    mode: "weight"
    miniblock: [1, 1, 16, 16]
    w_bit: 8
    in_bit: 6
  # conv_cfg:
  #   type: Conv2d
  linear_cfg:
    type: TeMPOBlockLinear
    mode: "weight"
    miniblock: [1, 1, 16, 16]
    w_bit: 8
    in_bit: 6
  # linear_cfg:
  #   type: Linear
  norm_cfg:
    type: BN2d
    affine: True
  act_cfg:
    type: ReLU
    inplace: True
  kernel_list: [64, 64, 64]
  kernel_size_list: [3, 3, 3]
  hidden_list: []
  stride_list: [1, 2, 1]
  padding_list: [1, 1, 1]
  pool_out_size: 5

debug:
  verboise: 1

dst_scheduler:
  death_rate: 0.5
  growth_death_ratio: 1.0
  death_rate_decay: cosine
  death_mode: magnitude
  growth_mode: gradient
  redistribution_mode: null
  spe_initial: null
  pruning_type: structure_col
  update_frequency: 1400
  skip_first_layer: True
  skip_last_layer: True
  T_max: 0.8
  density: 0.6
  max_combinations: 100
  keep_same: False
  init_mode: uniform
  power_choice_margin: 2
  splitter_biases: 90
  node_spacing: [20, 100] # um, row, col spacing in weight matrix