dataset:
  name: cifar10
  root: "/home/dataset/cifar10"
  train_valid_split_ratio: [0.9, 0.1]
  train_valid_split_seed: 1
  resize_mode: bicubic
  center_crop: 32
  n_test_samples: null
  n_valid_samples: null
  num_workers: 2
  img_height: 32
  img_width: 32
  in_channels: 3
  num_classes: 10
  transform: augmented
  shuffle: 0
  augment: null

criterion:
  name: ce

aux_criterion: null

optimizer:
  name: adamw
  lr: 0.02
  weight_decay: 0.01
  grad_clip_value: 1

scheduler:
  name: cosine
  lr_gamma: 0.99
  lr_min: 0

run:
  experiment: "default"
  n_epochs: 200
  batch_size: 32
  use_cuda: 1
  gpu_id: 0
  deterministic: 1
  random_state: 42
  log_interval: 200
  train_noise: 0
  grad_clip: False
  max_grad_value: 1
  do_distill: False
  compile: False

quantize:
  weight_bit: 32
  input_bit: 32

noise:
  phase_bias: 0
  phase_noise_std: 0
  gamma_noise_std: 0
  crosstalk_factor: 0
  random_state: 42
  weight_noise_std: 0.0

checkpoint:
  save_best_model_k: 3
  checkpoint_dir: "cifar10/vgg8/pretrain"
  model_comment: ""
  resume: 0
  restore_checkpoint: ""
  no_linear: 0

model:
  name: "TeMPO_VGG8"
  conv_cfg:
    type: Conv2d
  linear_cfg:
    type: Linear
  norm_cfg:
    type: BN2d
    affine: True
  act_cfg:
    type: ReLU
    inplace: True

debug:
  verbose: 1

